### ISSUE TITLE
Optical Drive bypass

### ISSUE THREAD

**Issue by proconsule** [DarkMatterCore/libusbhsfs#34]
The lib stall if a optical drive is connected with a usb pendrive/hdd. can you implement a bypass filter for optical 0x06 drives?

**Comment by DarkMatterCore** [comment]
Please provide a logfile generated by the latest version of the library so I can better debug this issue.

**Comment by proconsule** [comment]
[libusbhsfs.log](https://github.com/user-attachments/files/31232469/libusbhsfs.log)

[libusbhsfs.log-0.2.9.log](https://github.com/user-attachments/files/31232459/libusbhsfs.log-0.2.9.log)

Made with 0.2.9 and 0.2.10

**Comment by proconsule** [comment]
also just for your knowledge some old HDD drives only works on <= 0.2.9

**Comment by DarkMatterCore** [comment]
> also just for your knowledge some old HDD drives only works on <= 0.2.9

I'll need some logs for this, too.

I remember you mentioned it some time ago, but I could never reproduce the issue myself (not in the example application, nor in nxdumptool).

**Comment by proconsule** [comment]
Is hard because all my drives works, are some drives used by nxmp users, hard to debug also on my side to provide you a a decent log to analyze. If i found a drive on my hands that has this issue i will send you tons of log in any form

**Comment by DarkMatterCore** [comment]
@proconsule please test commit e74468d3655482c8d7c130e39cc6c1b1abb61352 and let me know if it fixes the issue.

**Comment by proconsule** [comment]
/usbhsfs_drive.c:539:12: error: variable 'max_burst' set but not used [-Werror=unused-but-set-variable=]
  539 |         u8 max_burst = (input ? usb_if_session->inf.inf.input_ss_endpoint_companion_descs[i].bMaxBurst : usb_if_session->inf.inf.output_ss_endpoint_companion_descs[i].bMaxBurst);

without -Werror 

usbhsfs_mount.c:569:42: error: 'UsbHsFsMountFlags_ProbeUnsupportedPartitionIDs' undeclared (first use in this function)
  569 |             if (g_fileSystemMountFlags & UsbHsFsMountFlags_ProbeUnsupportedPartitionIDs)

i removed the include from portlibs and now compiles. testing

**Comment by proconsule** [comment]
stall, here is the log 

[libusbhsfs.log](https://github.com/user-attachments/files/31239266/libusbhsfs.log)

**Comment by DarkMatterCore** [comment]
I don't see the stall you're talking about. The filter is now working as it should (the device is discarded and none of its LUN are initialized).

Are you using the usb:hs service separately too?

**Comment by proconsule** [comment]
i have a pendrive and a bd drive, the pendrive usb drive is not mounted.

**Comment by proconsule** [comment]
Alone without bd drive is mounted, here is the log with 2 drive and with only pendrive

[libusbhsfs.log](https://github.com/user-attachments/files/31239406/libusbhsfs.log)

**Comment by proconsule** [comment]
> Are you using the usb:hs service separately too?

No only usbhsfs.

**Comment by DarkMatterCore** [comment]
```
[2026-08-19 22:25:02.390707668] /source/usbhsfs_manager.c:604:usbHsFsManagerAtmosphereThreadFunc -> Interface available event triggered at startup (UMS devices already available).
[2026-08-19 22:25:02.390920400] /source/usbhsfs_manager.c:764:usbHsFsManagerResetMassStorageDevices -> usbHsQueryAvailableInterfaces returned 2 interface(s) matching our filter.
[2026-08-19 22:25:02.390940732] /source/usbhsfs_manager.c:780:usbHsFsManagerResetMassStorageDevices -> Resetting USB Mass Storage device with interface 1345912833.
[2026-08-19 22:25:02.391327924] /source/usbhsfs_manager.c:780:usbHsFsManagerResetMassStorageDevices -> Resetting USB Mass Storage device with interface 1345847296.
[2026-08-19 22:25:02.706216940] /source/usbhsfs_manager.c:621:usbHsFsManagerAtmosphereThreadFunc -> Interface available event triggered.
[2026-08-19 22:25:02.706236804] /source/usbhsfs_manager.c:630:usbHsFsManagerAtmosphereThreadFunc -> Current drive count: 0.
[2026-08-19 22:25:02.706363528] /source/usbhsfs_manager.c:824:usbHsFsManagerAddConnectedDriveContexts -> usbHsQueryAvailableInterfaces returned 1 interface(s) matching our filter.
```

When both units are connected, the pen drive doesn't get detected by `usbHsQueryAvailableInterfaces` after the interface reset at the start. This is a weird issue.

**Comment by proconsule** [comment]
Yes, on my lib i can suceful filter non optical device, and is working,  
My wish was to do the inverse on this, so i can use both (but obviusly not at the same time)

**Comment by DarkMatterCore** [comment]
In any case, this is no longer a stall issue (the new commit effectively fixed the problem), but rather, a USB interface detection issue.

> Yes, on my lib i can suceful filter non optical device, and is working, My wish was to do the inverse on this, so i can use both (but obviusly not at the same time)

Technically it is also working here (optical device is completely skipped now, as the logs show). But `usbHsQueryAvailableInterfaces` not returning all the data I expect it to return at that point is unexpected.

**Comment by proconsule** [comment]
Sorry for that strange issue but bd drives are 90% 0x06 subclass, instead of 0x02 that should be

**Comment by DarkMatterCore** [comment]
I was already handling this edge case scenario, but the secondary Inquiry request was making the library stall because the requested VPD page is not supported by the BD drive -- and the optical drive check was being carried out after that request.

I merely moved the check before the secondary Inquiry request.

**Comment by DarkMatterCore** [comment]
As for why a manual reset is carried out at the beginning if devices matching the BOT filter are detected:

https://github.com/DarkMatterCore/libusbhsfs/blob/e74468d3655482c8d7c130e39cc6c1b1abb61352/source/usbhsfs_manager.c#L600-L613

**Comment by proconsule** [comment]
Yes the stall is fixed, only a detection problem now

**Comment by proconsule** [comment]
Not releated, if you have free time and want to look at libusbdvd, i care a lot your opinion.
All fs parser are written from scratch

**Comment by DarkMatterCore** [comment]
> Yes the stall is fixed, only a detection problem now

Could you please test the latest commit using two regular USB mass storage devices at the same time? (e.g. two pen drives, a pen drive + a USB HDD, etc.).

I'm guessing the behavior for `usbHsQueryAvailableInterfaces` changed at some point within HOS without me noticing, but some confirmation would be nice.

**Comment by proconsule** [comment]
[libusbhsfs.log](https://github.com/user-attachments/files/31254581/libusbhsfs.log)

here is a pendrive and a usbhdd (m2 ssd) both are mounted and working

Sorry for delay but i think we are on very diffrent timezones (i am in italy)

**Comment by proconsule** [comment]
i also rebooted the switch and your changes did the job, maybe my switch was in an unexpeted state, this is the log

[libusbhsfs.log](https://github.com/user-attachments/files/31254782/libusbhsfs.log)

with a perndrive and a usb dvd, pendrive mounted and working. so i think issue is closed

**Comment by DarkMatterCore** [comment]
> i also rebooted the switch and your changes did the job, maybe my switch was in an unexpeted state, this is the log
> 
> [libusbhsfs.log](https://github.com/user-attachments/files/31254782/libusbhsfs.log)
> 
> with a perndrive and a usb dvd, pendrive mounted and working. so i think issue is closed

It's still weird. I swear `usbHsQueryAvailableInterfaces` was returning the same number of USB interfaces as the first call (2) after carrying out the bus reset (1) in prior HOS versions.

I'll mark this as fixed, but looking into why this specific IPC cmd is not working as it did before would be good.
